### ISSUE TITLE
Upgrade foundation

### ISSUE THREAD

**Issue by dereuromark** [cakephp/app#489] opened 2017-01-23 13:16 UTC
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

### What you did
Since there is no version notice anywhere about what the default template ships with in regard of Foundation, the Foundation docs lead to believe one can use http://foundation.zurb.com/sites/docs/callout.html etc.
But in fact we are using such an old version that none of those docs really apply anymore.
The header breaks, and also things like `em` highlighting as mentioned in Foundation docs doesn't work.

### What you expected to happen
We should upgrade to Foundation 6.x (6.3 ideally) or more clear point out the exact version we ship with, so people don't trip over this when trying ou the default app template.

**Comment by lorenzo** [comment] 2017-01-23 13:19
sure, do you think you have time to change the stylesheet?

**Comment by dereuromark** [comment] 2017-01-23 13:20
I don't, maybe someone can do that, including a small release version note in the base.css so it is also more easy to figure out the version which was "hardcoded" into the app webroot.

**Comment by ADmad** [comment] 2017-01-23 13:20
Besides the old version the more likely cause of the issue is we use a custom build of only a subset of the foundation classes not the full framework.

**Comment by dereuromark** [comment] 2017-01-23 13:21
Can't we use just the fullstack min file for simplicity reasons? The file size shouldn't matter here.

**Comment by ADmad** [comment] 2017-01-23 13:22
Instead of investing time in this I would rather we update the documentation stating that unless a user i gonna just do prototyping using the default bake templates, they should replace the included css files with their own.

**Comment by dereuromark** [comment] 2017-01-23 13:25
:-1: ADmad
We should ship with a proper default. And we should spend time here instead of saying "wont fix".
Users should be able to play with the current "default template" shipped - and we sure don't want to start our own Foundation docs just because of this, or say "sry, we have a broken layouting framework here".
That is not the reasonable thing IMO.

**Comment by cleptric** [comment] 2017-01-23 13:27
Also, we should know what @phpnut has in mind regarding the new layout. Will the new one still be based on Foundation? Maybe a switch to bootstrap?
If we can agree on something I'm, more than fine with doing a PR to upgrade Foundation.

**Comment by silakanveli** [comment] 2017-01-26 11:32
I have included whole minified foundation 5.5.3, seems to be working. I had problem getting some foundation components working originally. Would be fantastic if you could include foundation 6 by default.

**Comment by cleptric** [comment] 2017-01-26 11:54
I talked to @phpnut and the new design will still use Foundation.
So I can start to implement Foundation 6.

**Comment by ADmad** [comment] 2017-01-26 12:27
@cleptric Bear in mind the HTML generated by bake templates also relies on existing foundation classes so depending on what's changed between foundation 5 and 6 you might have to update bake templates too.

**Comment by inoas** [comment] 2017-01-26 12:31
That however means bake template results won't be bc anymore.
Next time I'd suggest not to stick to div-soup but use something like https://github.com/mblode/marx + display: flex, display: grid. That way things are agnostic.

**Comment by dereuromark** [comment] 2017-01-26 13:32
> So personally I'd stick with Foundation 5 during the 3.x life-cycle.

Why? The app is for fresh apps, and the bake plugin is as the name suggests an optional addon to the core, and has nothing to do with the core BC promises.
You can easily major here and people can continue to use the old 5er if needed, or just use their own bake templates even.

**Comment by inoas** [comment] 2017-01-26 14:11
Why?
Because bake will then not be BC with older apps. 

The real solution is not to rely on external frameworks, at least not if they cannot be applied unobstrusive/agonistic. This can be done for 4.0 app/bake.

**Comment by silakanveli** [comment] 2017-01-26 14:20
@ionas Understand that upgrading to Foundation 6 might break bake when baking not fresh apps. Im not sure how compatible version 6 is to 5??

Anyway, using foundation is beautiful solution for baking fresh app. Everything is responsive and lot of components to use. It is perfect for new user and new apps. Would imagine that with oven.php and baking anyone can have apps running in no time.

**Comment by bravo-kernel** [comment] 2017-01-26 15:32
FWIW my first good look at Foundation was because of the fact that it was used by Cake which to me sounded like a "recommendation". I have since tested most if not all other CSS frameworks and have come back to Foundation for exactly all the plus points mentioned above, most off all the fact that it's not obtrusive and actually quite agnostic. 

Changing it to 6.3 has my vote as well, I predict little to no bake fallout.

**Comment by lorenzo** [comment] 2017-01-26 15:35
I'd also like to upgrade the version

**Comment by markstory** [comment] 2017-01-26 18:40
If there were missing classnames after the upgrade to foundation 6, could we not implement those classnames in the CSS file that comes with the app skeleton? That would allow us to both upgrade and not require bake to change at the same time?

**Comment by dereuromark** [comment] 2017-01-26 18:50
Lets First find Out What changes will be required if any for bake templates. Then we will be able to talk about it less theoretically.

**Comment by cleptric** [comment] 2017-01-29 19:09
I took a look on what has to be changed:

**App**
- The `top-bar` markup/classes changed quite a bit, but it is easy to adopt 

**Bake Templates**
- We have to change the class of the `side-nav` to be a `menu vertical`. Also, the `heading` class is gone.
- Buttons needs a additional class `button`

**Further notes**
Tables are now `striped` by default. Looks not so bad.

Overall, it's pretty doable. But people that still use the old markup/foundation version will have to change some stuff as the default template will break when we update.

**Comment by dereuromark** [comment] 2017-01-29 19:12
@cleptric Sounds to be it could keep both classes and that would make it BC even then, right?

**Comment by cleptric** [comment] 2017-01-29 19:13
@dereuromark No, as the foundation 5.3 stuff is gone.

**Comment by dereuromark** [comment] 2017-01-29 19:14
I mean for the "bake" skeleton code for generating scaffolding :)
The app is for new stuff, no probs, but maybe it can be worth to keep BC for already baked projects instead of having to fork the templates here.
I don't mind either way, just putting the options on the table here.

**Comment by cleptric** [comment] 2017-01-29 19:16
In this case, yes :) 
Would be a little bit "dirty" but we can strip the old stuff out before cake 4.0 is released.

**Comment by markstory** [comment] 2017-01-30 02:05
@cleptric I'm less worried about existing applications breaking with new foundation. The concern I have is that if we were to update bake, then new bake and old app CSS would generate ugly/broken pages.

It sounds like upgrading to foundation 6 and creating the required missing classes will work though.

**Comment by dereuromark** [comment] 2017-03-31 19:19
Did anyone look into found6 here recently?
Seems like also alert messages are now "callouts" and other minor renames, should be doable.
We could even provide both classes to be max BC. And provide a small note on what can be safely removed once done upgraded to 6.

**Comment by inoas** [comment] 2017-08-18 23:03
I will repeat myself. Binding to a specific CSS framework was and is a bad choice.
But we can easily ship with https://github.com/mblode/marx ... add a very few custom styles and be done with it. Then there is no dependency because marx-css is classless.

**Comment by dereuromark** [comment] 2018-01-26 10:26
Are there any updates on Foundation6? Now that 5 becomes more and more outdated and also doesn't seem to work anymore with e.g. Jquery3 and alike.

**Comment by markstory** [comment] 2018-01-26 16:24
@dereuromark I don't think there are any short term plans to upgrade which foundation we're using. I personally don't have the time right now to take on a project like that right now.

**Comment by vnt** [comment] 2018-03-12 19:54
I hope that you can update Bake to Foundation 6. Thanks a lot

**Comment by chtheis** [comment] 2019-01-02 12:32
Just my 2 cent:
I came across this discussion when I searched how to integrate CakePHP with Foundation. What I learned is that this is no easy task.

I consider CakePHP primarily a backend, but users will want to add a frontend (aka CSS + JS) framework, esp. when it comes to make their project responsive. No one would like to start from scratch,.

I see your point that CakePHP should not depend on a specific version of an external framework. But would it be possible to offer different skeletons for different frameworks / versions? E.g. move the Templates / .twig-files to a framework-specific subfolder. E.g. you could have one zurb/fs5 for old Foundation 5 projects, zurb/fs6 for new Foundation 6, twitter/bs4 for Bootstrap, and so on. The bake command would get a parameter to choose a framework / version.

These frameworks could even be "out-sourced" into their own repositories and develop at their own pace.

**Comment by markstory** [comment] 2019-01-03 20:18
Bake does support 'themes' which allow end users to pick different templates to use when generating code. I don't know of many bake themes out in the wild though.

**Comment by chtheis** [comment] 2019-01-04 07:59
Am 03.01.2019 um 21:18 schrieb Mark Story:
> Bake does support 'themes' which allow end users to pick different 
> templates to use when generating code. I don't know of many bake themes 
> out in the wild though.

Hmmm ...
I never thought of themes, I'v never used them. And throwing themes at 
first-time users who just want to start makes the learning curve even 
steeper. But good to know the stuff is almost there.

I thought more along the line to factor out the framework dependent code 
so that maintaining it will be easier. That does not only include the 
bake templates but affects also base.css and cake.css. And the templates 
the FormHelper is using.

Anyway, that was just an idea I had when I read the discussion. I guess 
switching to F6 won't be too difficult for a user who stared with 3.x 
anyway.

**Comment by vnt** [comment] 2019-01-04 10:30
My favorite framework is twitter bootstrap, I think it's also the most used one.

**Comment by dereuromark** [comment] 2019-01-04 10:34
But as we said, twitter is off the table for its markup overhead. There is a plugin for it to easily opt-in here.
Guys, kee it simple.

A) upgrade to foundation 6 as good default
B) this way, people have a boilerplate that is easy to switch to anything else
C) also provides a good default to actually keep for most basic backend apps.

Sounds like the perfect compromise of all directions to me still.

**Comment by chtheis** [comment] 2019-01-04 10:55
Am 04.01.2019 um 11:34 schrieb Mark Sch.:
> But as we said, twitter is off the table for its markup overhead. There 
> is a plugin for it to easily opt-in here.
> Guys, kee it simple.

I didn't want to start a framework war.
Just, when you change the code, and you have to do something, consider 
doing it in a way that makes it easier in the future to adapt when the 
chosen framework changes.

Not supporting any framework may not be the best idea: I started with 
CakePHP 1.3, when everything was in cake.generic.css, and getting in 
Foundation is ... painful.

**Comment by inoas** [comment] 2019-01-04 10:57
It has always been a a good to be frontend framework agnostic.

Good choices to be are MarxCSS https://github.com/mblode/marx and Milligram https://milligram.io/
Latter has recently been adopted by https://github.com/phoenixframework/phoenix 1.4

**Comment by ADmad** [comment] 2019-01-04 11:22
I concur with @dereuromark.

**Comment by dereuromark** [comment] 2019-01-04 11:38
@inoas Interested in making a PR to see some results?

**Comment by ADmad** [comment] 2019-01-04 12:00
Just want to add that it would be best to do the upgrade for `4.x` branch of skeleton app (which is meant for CakePHP 4.0).

**Comment by dereuromark** [comment] 2019-01-28 18:53
Looks like someone was already working on some foundation 6 support: https://github.com/t73biz/cakephp-turntable

**Comment by t73biz** [comment] 2019-01-29 15:17
I have released version 1.0.0 of this as a plugin package. It's backed by tests, but I'm sure there may be improvements made to it, and am glad to take PR's or even tickets to update/upgrade it.

There is a Command `glaze` to symlink the foundation 6 assets to an applications webroot, and it also has some baking templates available.

Suggestions are most welcome.

**Comment by dereuromark** [comment] 2019-01-29 15:31
It looks to me that your plugin FormHelper actually adds quite a bit of boilerplate markup now for F6.
Is this a requirement compared to old F5?
Then this would make an argument to keep it as plugin opt-in (similar to BS4) and indeed use a more "blank" and true markup-less solution as proposed above, e.g. milligram, for cakephp/app skeleton.

**Comment by t73biz** [comment] 2019-01-29 17:21
First let me say that I'm by no means a Foundation 6 expert. That being said, I've implemented the bake templates in a way that follows along with the examples given in the foundation documentation.

For example, in the docs for Forms, it states that fieldset elements are no longer styled based off of the element declaration, but rather a class declaration of fieldset. https://foundation.zurb.com/sites/docs/forms.html#fieldset-styles

Given the above example, and for lack of completely reading the entire docs, it's plausible that the rest of foundation 6 has taken a similar approach to styling other elements.

Another example, https://foundation.zurb.com/sites/docs/forms.html#text-inputs shows that the intended div wrapper for labels and elements has specific width styling applied to it, and that generic wrapping, while acceptable, would not allow for proper responsiveness, as is used by the XY Grid pattern, implemented in Foundation 6.

So to the point of having a "simple"/plain bake template, it is my belief that Foundation 6 would not be a proper library to include into core, if this is the direction that is to be used fore CakePHP core.

Personally, I like Foundation 6 and what it offers, which is why I have used it for my package.

**Comment by ADmad** [comment] 2019-01-29 17:58
The extra classes are required only for grid display which would be necessary using any framework. So "normal" forms with inputs below labels like bake generates I am pretty sure no extra classes are required with Foundation 6.

**Comment by t73biz** [comment] 2019-01-29 18:00
@ADmad is correct in that the extra classes are only required for grid display, and the default behaviour is label above input element

**Comment by cleptric** [comment] 2019-05-28 10:32
We recently merged #683 so I'll close this.

**Closed by cleptric** 2019-05-28 10:32 UTC
Labels: Enhancement
