### ISSUE TITLE
Insufficient file permissions post install

### ISSUE THREAD

**Issue by SplicePHP** [cakephp/app#408] opened 2016-08-02 09:37 UTC
After installing the file permissions are set to 757 instead of 777.
757 does not seem to be writable by apache on my system.
Here is a quick synopsis of my setup.
I am running Linux Mint 18 with php 7.0.
I have set up a virtual host in my home directory (~/www) and gave www-data group access to my account.
The install is run in the command line as my default user account.
The problem occurs here:
Line 159: [PROJECT]/src/Console/Installer.php
```
$worldWritable = bindec('0000000111');
```
bindec resolves to 7

Logic would presume that group access would imply world access but this doesn't seem to be the case for some reason.
If group has no write access and the apache server is a part of the group it can't write to the directories.

Changing $worldWritable to ```bindec('1100001001')``` or ```777``` fixes the issue on my system.

Is there any reason for the permissions not to be set to 777 instead of 757?

Thanks.

**Comment by thinkingmedia** [comment] 2016-08-02 09:49
My `tmp` and `log` folders are `775` after running the installer (Ubuntu 14)

That gives write access to the group `drwxrwxr-x`

The installer doesn't change permissions on the `webroot`

**Comment by SplicePHP** [comment] 2016-08-02 10:37
That is strange, not sure why the permissions would be different.
Can't fix the problem if it can't be reproduced.
Will try to see if I can figure out why this is the case.

Here is my exact system config if anyone is interested:
System: Asus H170-Plus D3 (lga 1151), CPU G4400 (3.3 dual core), 14gig ram, Ati HD600 Eyefinity 
OS: Linux Mint 18 Sarah 64 bit Cinnamon with all updates intalled
(Not in virtual box, running as primary OS) 
This is a fresh install, everything was installed last week.

Here is the relevant package configuration as I set it up:
(This should be run-able as a bash script after install but I haven't tested it)
I think this is everything.
```
Server Config:
sudo apt-get update
sudo apt-get upgrade

#Install Git
sudo apt-get install git-all

#Install Webserver
sudo apt-get install apache2
sudo apt-get install python-software-properties
sudo add-apt-repository ppa:ondrej/php
sudo apt-get update
sudo apt-get install -y php7.0
sudo apt-get install php7.0-mysql php7.0-curl php7.0-json php7.0-cgi php7.0-intl php7.0-mbstring php7.0-gd php7.0-mcrypt

#Enable Module Rewrite
sudo a2enmod rewrite

## Install MySQL
sudo apt-get install mysql-server phpmyadmin
##Config MySql Defaults
sudo sh -c "cat >> /etc/mysql/mysql.cnf" <<-EOF
[client]
default-character-set=utf8

[mysql]
default-character-set=utf8

[mysqld]
init_connect='SET collation_connection = utf8_unicode_ci' 
init_connect='SET NAMES utf8' 
character-set-server=utf8 
collation-server=utf8_unicode_ci 
skip-character-set-client-handshake
EOF


#USER CONFIG
sudo chown -R www-data:www-data /var/www
sudo usermod -a -G www-data $USER
sudo chmod 775 /var/www -R

#Composer Setup
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('SHA384', 'composer-setup.php') === 'e115a8dc7871f15d853148a7fbac7da27d6c0030b848d9b3dc09e2a0388afed865e6a3d6b3c0fad45c48e2b5fc1196ae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"

#Post composer install
sudo mv composer.phar /usr/local/bin/composer
sudo composer self-update
sudo chown -Rv $USER:root ~/.composer
sudo usermod -a -G www-data $USER

mkdir ~/www

#Append Virtual Host
sudo sh -c "cat >> /etc/apache2/sites-enabled/000-default.conf" <<-EOF
<VirtualHost *:80>
    DocumentRoot "/home/$USER/www/"
    ServerName $USER
	<Directory /home/$USER/www/>
		Options Indexes FollowSymLinks Includes ExecCGI
		AllowOverride All
		Require all granted
	</Directory>
</VirtualHost>
EOF

#Setup CakePHP
cd ~/www
composer create-project --prefer-dist cakephp/app project
```
In browser navigate to http://$USER/project

**Comment by thinkingmedia** [comment] 2016-08-02 10:58
In your issue description you ask if it should be set to `777` but I don't think it should be. As that will give everyone write access. `775` is the right permissions as that gives the owner and group write access, and everyone read only access.

Permission values should be the same across all flavors of Linux.

I'll run composer create-project on my build machine and see what happens.

**Comment by SplicePHP** [comment] 2016-08-02 11:02
Thanks, you are right. It should be 775. I assumed that it was trying to set the permissions to 777 since it was setting world to 7. Thought 777 was a bit too permissive.

**Comment by thinkingmedia** [comment] 2016-08-02 11:03
Oh I got `777` on my `logs` and `tmp` folders.

```
drwxrwxr-x 11 mathew mathew  4096 Aug  2 06:59 .
drwxrwxr-x  3 mathew mathew  4096 Aug  2 06:58 ..
drwxrwxr-x  2 mathew mathew  4096 Apr 27 00:45 bin
-rw-rw-r--  1 mathew mathew  1280 Apr 27 00:45 composer.json
-rw-rw-r--  1 mathew mathew 43642 Aug  2 06:59 composer.lock
drwxrwxr-x  3 mathew mathew  4096 Aug  2 06:59 config
-rw-rw-r--  1 mathew mathew   329 Apr 27 00:45 .editorconfig
-rw-rw-r--  1 mathew mathew   772 Apr 27 00:45 .gitattributes
-rw-rw-r--  1 mathew mathew    41 Apr 27 00:45 .gitignore
-rw-rw-r--  1 mathew mathew   140 Apr 27 00:45 .htaccess
-rw-rw-r--  1 mathew mathew   648 Apr 27 00:45 index.php
drwxrwxrwx  2 mathew mathew  4096 Apr 27 00:45 logs
-rw-rw-r--  1 mathew mathew  1202 Apr 27 00:45 phpunit.xml.dist
drwxrwxr-x  2 mathew mathew  4096 Apr 27 00:45 plugins
-rw-rw-r--  1 mathew mathew  1015 Apr 27 00:45 README.md
drwxrwxr-x  8 mathew mathew  4096 Apr 27 00:45 src
drwxrwxr-x  4 mathew mathew  4096 Apr 27 00:45 tests
drwxrwxrwx  5 mathew mathew  4096 Apr 27 00:45 tmp
-rw-rw-r--  1 mathew mathew   321 Apr 27 00:45 .travis.yml
drwxrwxr-x 15 mathew mathew  4096 Aug  2 06:59 vendor
drwxrwxr-x  5 mathew mathew  4096 Apr 27 00:45 webroot
```

Verified with stat

```
mathew@build:~/test/project$ stat -c "%a %n" *
775 bin
664 composer.json
664 composer.lock
775 config
664 index.php
777 logs
664 phpunit.xml.dist
775 plugins
664 README.md
775 src
775 tests
777 tmp
775 vendor
775 webroot
```

I'm wondering if this is a good thing or bad thing.

@markstory do you know why we would want the `tmp` or `logs` as `777`?

**Comment by thinkingmedia** [comment] 2016-08-02 11:09
Oh I remember.

If you run `bin/cake bake` it will touch the `tmp` and `log` folders as the current user. Bake will trigger the updating of the ORM caches and stuff like that.

So if you change it to `775` you have to be using a user in the same group (i.e. `www-data`) from the command line. I've tried to this in the past and it was a pain.

Also, I've had shell tasks that do admin stuff. So sometimes I run shells with root like `sudo bin/cake stuff`. This can be bad as it creates `root:root` owned files in the `tmp` folder. So I run the installer afterwards or change the ownership manually.

Yeah, I would leave it as `777` unless you know no other groups will ever touch them.

**Comment by thinkingmedia** [comment] 2016-08-02 11:15
> After installing the file permissions are set to 757 instead of 777.

Okay, I got distracted. The above is what your problem is.

Are your other files after running composer set to 755 instead of 775?

I'm thinking that 755 is the default permissions for your user account.

http://unix.stackexchange.com/questions/1314/how-to-set-default-file-permissions-for-all-folders-files-in-a-directory

**Comment by SplicePHP** [comment] 2016-08-02 11:16
I reset my apache.conf file to its default and restarted the server to make sure onthing I did there could have caused any issues. Here is the ll output i get after install:
```
drwxr-xr-x 11 splice splice  4096 Aug  2 12:57 ./
drwxrwxr-x  7 splice splice  4096 Aug  2 12:56 ../
drwxr-xr-x  2 splice splice  4096 Apr 27 06:45 bin/
-rw-r--r--  1 splice splice  1280 Apr 27 06:45 composer.json
-rw-r--r--  1 splice splice 43642 Aug  2 12:57 composer.lock
drwxr-xr-x  3 splice splice  4096 Aug  2 12:57 config/
-rw-r--r--  1 splice splice   329 Apr 27 06:45 .editorconfig
-rw-r--r--  1 splice splice   772 Apr 27 06:45 .gitattributes
-rw-r--r--  1 splice splice    41 Apr 27 06:45 .gitignore
-rw-r--r--  1 splice splice   140 Apr 27 06:45 .htaccess
-rw-r--r--  1 splice splice   648 Apr 27 06:45 index.php
drwxr-xrwx  2 splice splice  4096 Apr 27 06:45 logs/
-rw-r--r--  1 splice splice  1202 Apr 27 06:45 phpunit.xml.dist
drwxr-xr-x  2 splice splice  4096 Apr 27 06:45 plugins/
-rw-r--r--  1 splice splice  1015 Apr 27 06:45 README.md
drwxr-xr-x  8 splice splice  4096 Apr 27 06:45 src/
drwxr-xr-x  4 splice splice  4096 Apr 27 06:45 tests/
drwxr-xrwx  5 splice splice  4096 Apr 27 06:45 tmp/
-rw-r--r--  1 splice splice   321 Apr 27 06:45 .travis.yml
drwxr-xr-x 15 splice splice  4096 Aug  2 12:57 vendor/
drwxr-xr-x  5 splice splice  4096 Apr 27 06:45 webroot/
```

**Comment by thinkingmedia** [comment] 2016-08-02 11:23
What permissions do you get if you create a file?

```
$ touch test
$ ls -la
```

**Comment by SplicePHP** [comment] 2016-08-02 11:23
-rw-r--r--  1 splice splice     0 Aug  2 13:23 test

**Comment by thinkingmedia** [comment] 2016-08-02 11:24
Yup, that's your problem. The default permissions for the `splice` user do not give write permissions to the group.

**Comment by SplicePHP** [comment] 2016-08-02 11:24
Okay thanks, how do I fix it?

**Comment by thinkingmedia** [comment] 2016-08-02 11:30
I'm not sure how to fix it, but I think you need to setup permission defaults for the directory you're working in.

So if you are installing the app into the `/var/www` folder, then you would add write defaults like this.

```
setfacl -d -m g::rwx /var/www 
```

Afterwards any files created in that folder should have `rwx` permissions for the group.

**Comment by SplicePHP** [comment] 2016-08-02 11:35
Thanks a lot. I am a bit new to the linux environment. Kicked windows and osx like a bad habbit last month. Still trying to get the hang of permissions. Will try it now and confirm if all is working.

**Comment by thinkingmedia** [comment] 2016-08-02 11:42
It's purely an issue with Linux Mint which I've never used. Ubuntu has different defaults and that's one of the issues with Linux is that all the flavors have their own ways of doing things.

**Comment by SplicePHP** [comment] 2016-08-02 11:44
setfacl didn't seem to change anything. Gonna reboot and check if the issue persists. Will google to find the best solution for default permission. I will post an update here as soon as I get it working properly for future reference.

Thanks a lot for the help, think I should be able to figure this out now.

**Comment by SplicePHP** [comment] 2016-08-02 11:53
Reboot seems to have done the trick. Everything seems to be working now.

**Comment by SplicePHP** [comment] 2016-08-02 12:23
Think I spoke to soon. Accidentally checked the permissions of the wrong build test. Touch and mkdir now creates permissions correctly but creating files with composer seems to be causing the problem now.

I tried the global composer and created a fresh composer.phar in my www and ran it from there.

If I install with composer I get the following file permissions:
```
drwxrwxr-x+ 11 splice splice  4096 Aug  2 14:14 ./
drwxrwxr-x+ 14 splice splice  4096 Aug  2 14:14 ../
drwxr-xr-x+  2 splice splice  4096 Apr 27 06:45 bin/
-rw-r--r--   1 splice splice  1280 Apr 27 06:45 composer.json
-rw-rw-r--   1 splice splice 43642 Aug  2 14:14 composer.lock
drwxr-xr-x+  3 splice splice  4096 Aug  2 14:14 config/
-rw-r--r--   1 splice splice   329 Apr 27 06:45 .editorconfig
-rw-r--r--   1 splice splice   772 Apr 27 06:45 .gitattributes
-rw-r--r--   1 splice splice    41 Apr 27 06:45 .gitignore
-rw-r--r--   1 splice splice   140 Apr 27 06:45 .htaccess
-rw-r--r--   1 splice splice   648 Apr 27 06:45 index.php
drwxr-xrwx+  2 splice splice  4096 Apr 27 06:45 logs/
-rw-r--r--   1 splice splice  1202 Apr 27 06:45 phpunit.xml.dist
drwxr-xr-x+  2 splice splice  4096 Apr 27 06:45 plugins/
-rw-r--r--   1 splice splice  1015 Apr 27 06:45 README.md
drwxr-xr-x+  8 splice splice  4096 Apr 27 06:45 src/
drwxr-xr-x+  4 splice splice  4096 Apr 27 06:45 tests/
drwxr-xrwx+  5 splice splice  4096 Apr 27 06:45 tmp/
-rw-r--r--   1 splice splice   321 Apr 27 06:45 .travis.yml
drwxr-xr-x+ 15 splice splice  4096 Aug  2 14:14 vendor/
drwxr-xr-x+  5 splice splice  4096 Apr 27 06:45 webroot/
```
If I do a git clone I get these permissions:
```
drwxrwxr-x+ 12 splice splice 4096 Aug  2 14:13 ./
drwxrwxr-x+ 14 splice splice 4096 Aug  2 14:14 ../
drwxrwxr-x+  2 splice splice 4096 Aug  2 14:09 bin/
-rw-rw-r--   1 splice splice 1280 Aug  2 14:09 composer.json
drwxrwxr-x+  3 splice splice 4096 Aug  2 14:09 config/
-rw-rw-r--   1 splice splice  329 Aug  2 14:09 .editorconfig
drwxrwxr-x+  8 splice splice 4096 Aug  2 14:09 .git/
-rw-rw-r--   1 splice splice  772 Aug  2 14:09 .gitattributes
-rw-rw-r--   1 splice splice   41 Aug  2 14:09 .gitignore
-rw-rw-r--   1 splice splice  303 Aug  2 14:09 .htaccess
-rw-rw-r--   1 splice splice  648 Aug  2 14:09 index.php
drwxrwxr-x+  2 splice splice 4096 Aug  2 14:09 logs/
-rw-rw-r--   1 splice splice 1202 Aug  2 14:09 phpunit.xml.dist
drwxrwxr-x+  2 splice splice 4096 Aug  2 14:09 plugins/
-rw-rw-r--   1 splice splice 1015 Aug  2 14:09 README.md
drwxrwxr-x+  8 splice splice 4096 Aug  2 14:09 src/
drwxrwxr-x+  4 splice splice 4096 Aug  2 14:09 tests/
drwxrwxr-x+  5 splice splice 4096 Aug  2 14:09 tmp/
-rw-rw-r--   1 splice splice  321 Aug  2 14:09 .travis.yml
drwxrwxr-x+  2 splice splice 4096 Aug  2 14:09 vendor/
drwxrwxr-x+  5 splice splice 4096 Aug  2 14:09 webroot/
```
Will investigate further and report my findings.

**Comment by AD7six** [comment] 2016-08-02 13:24
> After installing the file permissions are set to 757 instead of 777.

AFAIK nothing is setting _file_ permissions in the installer process, this is down to your own umask.

> Oh I got 777 on my logs and tmp folders.

These are the only paths that the installer modifies and [it only opperates on folders, not files](https://github.com/cakephp/app/blob/master/src/Console/Installer.php#L146-L163).

Closing as the problem isn't related to the installer, or anything in CakePHP's scope

**Closed by AD7six** 2016-08-02 13:24 UTC

**Comment by thinkingmedia** [comment] 2016-08-02 13:32
Maybe composer is owned by a different group and Linux is using the defaults for that group. I'm not sure exactly how that works.

I would just live with it for now, and after using composer fix the group permissions using `chmod`

**Comment by sitedyno** [comment] 2016-08-02 14:00
As AD7six said this is down to the umask on /home/$USER

Instead of changing the umask and allowing the web server to access files in your home directory you may want to consider **Solution 1** here: http://askubuntu.com/a/46371 It works well 'for me'.

**Comment by SplicePHP** [comment] 2016-08-02 14:03
Thanks, I will leave my system as is and use chmod to fix the permissions for now and keep an eye on files created by the framework for any further permission anomalies, because unreliable file permission settings could have devastating implications on a live server. Will run some test on File and Folder classes to make sure there aren't any similar issues occurring there. I doubt there will be any issues but better to be sure. [ Thanks sitedyno, will try your suggestion once I am done testing ]

**Comment by sitedyno** [comment] 2016-08-02 14:11
Just for clarification umask in this instance means `file mode creation mask` and limits the permissions on newly created files/directories. This is enforced by the **Operating System** so apache/php/cake will not be able to set all possible permissions. They may appear to be buggy, but they are actually limited by the OS.

**Comment by thinkingmedia** [comment] 2016-08-03 13:36
Linux is the operating system that makes you feel smart for using it, but forever stupid while trying to use it.
