### ISSUE TITLE
I18n error passing variable encoding euc-jp to translator

### ISSUE THREAD

**Issue by anhtuank7c** [cakephp/app#322] opened 2016-01-07 03:02 UTC
Dear all.
My application have to run with encoding EUC-JP.
I did setup:
```
app.php

App.encoding = "EUC-JP"
Datasource.default.encoding = 'ujis'
```
Everything was fine except passing variable to translator like this:
```
echo mb_detect_encoding($user->name); // EUC-JP
echo __('Hi {0}', $user->name); // $user->name is euc-jp encoding
// In error log i see $user->name = \xB4\xC9\xCD\xFD\xBC\xD4 instead of 管理者
```

The error:
```
2016-01-07 11:44:18 Error: [Aura\Intl\Exception\CannotFormat] Invalid UTF-8 data in string argument: '´ÉÍý¼Ô': U_INVALID_CHAR_FOUND
Request URL: /forgot-password
Stack Trace:
#0 D:\ownCloud\Project\sbd2\vendor\cakephp\cakephp\src\I18n\Formatter\IcuFormatter.php(51): Cake\I18n\Formatter\IcuFormatter->_formatMessage('ja_JP', 'Hi, {0}', Array)
#1 D:\ownCloud\Project\sbd2\vendor\aura\intl\src\Aura\Intl\Translator.php(142): Cake\I18n\Formatter\IcuFormatter->format('ja_JP', 'Hi, {0}', Array)
#2 D:\ownCloud\Project\sbd2\vendor\cakephp\cakephp\src\I18n\functions.php(33): Aura\Intl\Translator->translate('Hi, {0}', Array)
#3 D:\ownCloud\Project\sbd2\src\Template\Email\html\user\forgot_password.ctp(10): __('Hi, {0}', '\xB4\xC9\xCD\xFD\xBC\xD4')
```

May aura force to use UTF-8 for translator?

**Comment by markstory** [comment] 2016-01-07 03:20
How could someone reproduce this? I've never used euc-jp encoded data before. Does the byte sequence of `\xB4\xC9\xCD\xFD\xBC\xD4` represent the data you wanted (管理者) ?

**Comment by anhtuank7c** [comment] 2016-01-07 03:59
This is original string in euc-jp encoding: `管理者`
I direct pass to function _(), then they become to `\xB4\xC9\xCD\xFD\xBC\xD4`
I don't know the byte is represent of `管理者`. I'm not Japanese guy.
One thing strange here is i set application encoding to euc-jp, the template i was convert to euc-jp encoding too, but `aura` said not valid `UTF-8` data.
I'm research Aura but cannot found where they use `UTF-8` encoding.

....

**Comment by gr-terada** [comment] 2016-01-08 00:39
FYI:
`\xB4\xC9\xCD\xFD\xBC\xD4` is `管理者` of EUC-JP.
`´ÉÍý¼Ô` is a mime-decoded `管理者` of EUC-JP.
`管理者` means  "administrator".

**Comment by markstory** [comment] 2016-01-08 03:10
While that exception is an Aura exception, it is not being emitted from Aura. Instead it coming from the IcuFormatter in CakePHP. The [following context](https://github.com/cakephp/cakephp/blob/master/src/I18n/Formatter/IcuFormatter.php#L90-L102) shows where that error is coming from. Based on that code it looks like `MessageFormatter` provided by intl does not support non-UTF8 compatible encodings.

**Comment by anhtuank7c** [comment] 2016-01-08 15:02
When does not passing variable, `MessageFormatter` still working well.
```
echo __('administrator'); //管理者
// This function still working well
```
I just face this problem when passing euc-jp encoding variable.

**Comment by markstory** [comment] 2016-01-08 22:34
I don't think euc-jp is going to work well with intl.

**Comment by anhtuank7c** [comment] 2016-01-09 03:10
@markstory This is my sign in page.
![signin](https://cloud.githubusercontent.com/assets/3163410/12214061/fdd629a4-b6c9-11e5-9666-1c43a7cdd010.PNG)

**Comment by renan** [comment] 2016-01-11 16:30
Looking at the php-src code it does seems it can only handle UTF-8 parameters, check it [here](https://github.com/php/php-src/blob/master/ext/intl/msgformat/msgformat_helpers.cpp#L415-L428). I also tested it on separate script, which shows this is not really a CakePHP issue but rather PHP/INTL itself, check it [here](https://3v4l.org/jOWCt).

If you do have a chance I would suggest to use UTF-8 instead, as the Wiki page for EUC-JP says:
> Modern applications are more likely to use UTF-8, which supports all of the glyphs of the EUC codes, and more, and is generally more portable with fewer vendor deviations and errors.

**Comment by ADmad** [comment] 2016-01-11 16:33
Closing as this is a PHP/INTL issue and nothing we can do about it.

**Closed by ADmad** 2016-01-11 16:33 UTC
