### ISSUE TITLE
Number::toReadableSize get error when filesize < 1024 B

### ISSUE THREAD

**Issue by anhtuank7c** [cakephp/app#345] opened 2016-03-01 14:41 UTC
When use Number::toReadableSize(0)
If input number greater than 1024 B, it's working good.
CakePHP 3.2.3
![number](https://cloud.githubusercontent.com/assets/3163410/13430115/4a7ca5da-dff6-11e5-9fae-5387c6a86b8c.PNG)

Error log:
`2016-03-01 23:37:30 Error: [Aura\Intl\Exception\CannotInstantiateFormatter] msgfmt_create: message formatter creation failed: U_ILLEGAL_ARGUMENT_ERROR
Request URL: /admin/file-manager/index/2016/01
Referer URL: http://localhost:8765/admin/file-manager/index/2016/01
Stack Trace:
#0 D:\ownCloud\Project\dgtw\vendor\cakephp\cakephp\src\I18n\Formatter\IcuFormatter.php(71): Cake\I18n\Formatter\IcuFormatter->_formatMessage('ja_JP', '', Array)
#1 D:\ownCloud\Project\dgtw\vendor\aura\intl\src\Aura\Intl\Translator.php(142): Cake\I18n\Formatter\IcuFormatter->format('ja_JP', Array, Array)
#2 D:\ownCloud\Project\dgtw\vendor\cakephp\cakephp\src\I18n\functions.php(110): Aura\Intl\Translator->translate('{0,number,integ...', Array)
#3 D:\ownCloud\Project\dgtw\vendor\cakephp\cakephp\src\I18n\Number.php(87): __dn('cake', '{0,number,integ...', '{0,number,integ...', 1023, 1023)
#4 D:\ownCloud\Project\dgtw\src\Template\Admin\FileManager\index.ctp(50): Cake\I18n\Number::toReadableSize(1023)
#5 D:\ownCloud\Project\dgtw\vendor\cakephp\cakephp\src\View\View.php(992): include('D:\\ownCloud\\Pro...')
#6 D:\ownCloud\Project\dgtw\vendor\cakephp\cakephp\src\View\View.php(952): Cake\View\View->_evaluate('D:\\ownCloud\\Pro...', Array)
#7 D:\ownCloud\Project\dgtw\vendor\cakephp\cakephp\src\View\View.php(587): Cake\View\View->_render('D:\\ownCloud\\Pro...')
#8 D:\ownCloud\Project\dgtw\vendor\cakephp\cakephp\src\Controller\Controller.php(611): Cake\View\View->render(NULL, NULL)
#9 D:\ownCloud\Project\dgtw\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(120): Cake\Controller\Controller->render()
#10 D:\ownCloud\Project\dgtw\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\Admin\FileManagerController))
#11 D:\ownCloud\Project\dgtw\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#12 {main}
`

**Comment by dereuromark** [comment] 2016-03-01 14:52
This is the wrong bug tracker. https://github.com/cakephp/cakephp/issues is for framework related issues.

**Comment by chinpei215** [comment] 2016-03-01 15:55
I am guessing it is the same issue as cakephp/cakephp#8373
Personally, I couldn't reproduce it in my environment.
```php
echo Cake\I18n\Number::toReadableSize(0);
```
```
0バイト
```
But it seems to be related with ja_JP locale I translated. I used multi-bytes for the msgid `{0,number,integer} Byte`. But I didn't use the field `{0,number,#,###.##} KB` or grater.

**Comment by chinpei215** [comment] 2016-03-01 16:06
I could reproduce it now if I use `ini_set('intl.default_locale', 'ru_RU');` Probably, it is for the reason @arneefreeman mentioned.

**Comment by markstory** [comment] 2016-03-01 17:07
Closing as this is in the wrong repo, and we have an existing issue around missing plural forms.

**Closed by markstory** 2016-03-01 17:07 UTC
Labels: Defect
