### ISSUE TITLE
Deprecation warning breaks application

### ISSUE THREAD

**Issue by smarek** [cakephp/app#608] opened 2018-05-21 18:02 UTC
Hey, after upgrading from 3.4.x to 3.6.x, deprecation warning within "Cake\Network\Request" breaks most of the functions of the application (ajax, rendering here and there, ...)

Deprecation warning looks like this:
```
Deprecated (16384): Use Cake\Http\ServerRequest instead of Cake\Network\Request. - /var/www/cake_app/vendor/composer/ClassLoader.php, line: 444
```

What should be fixed in my opinion, is to not throw this warning when the class is loaded using "vendor/composer/ClassLoader.php" without any direct dependency from application, because that is what is my case.

Because I just did an upgrade, I want to see the deprecation warnings so I can fix those, however this is not in my code, so I should not be bothered with it.

Somehow this class gets loaded using composer class-loader, even when my source, does not refer to the specific class in any way.

Is this fixable, meant to work this way, or is there something broken in my application, after upgrading the cakephp and depdendencies?

Thank you!

**Comment by dereuromark** [comment] 2018-05-21 18:20
https://book.cakephp.org/3.0/en/appendices/3-6-migration-guide.html#disabling-deprecation-warnings

**Comment by smarek** [comment] 2018-05-21 18:53
I know, i stated in initial post, i want to keep deprecation warnings on,
so i can fix them, however, this one i should not fix myself

**Comment by dereuromark** [comment] 2018-05-21 18:58
If this is based on usage of the deprecated class in your code, it very much is sth you need to fix yourself.
This is not a framework issue - mot likely. The stack reveals sure more, but the statement you linked is sure not the root cause.

**Comment by smarek** [comment] 2018-05-21 19:55
Sorry for not including full stacktrace, does this help?
```
$message = 'Use Cake\Http\ServerRequest instead of Cake\Network\Request. - /var/www/cake_app/vendor/composer/ClassLoader.php, line: 444
 You can disable deprecation warnings by setting `Error.errorLevel` to `E_ALL & ~E_USER_DEPRECATED` in your config/app.php.'
$stackFrame = (int) 1
$trace = [
	(int) 0 => [
		'file' => '/var/www/cake_app/vendor/cakephp/cakephp/src/Network/Request.php',
		'line' => (int) 4,
		'function' => 'deprecationWarning',
		'args' => [
			(int) 0 => 'Use Cake\Http\ServerRequest instead of Cake\Network\Request.'
		]
	],
	(int) 1 => [
		'file' => '/var/www/cake_app/vendor/composer/ClassLoader.php',
		'line' => (int) 444,
		'args' => [
			(int) 0 => '/var/www/cake_app/vendor/cakephp/cakephp/src/Network/Request.php'
		],
		'function' => 'include'
	],
	(int) 2 => [
		'file' => '/var/www/cake_app/vendor/composer/ClassLoader.php',
		'line' => (int) 322,
		'function' => 'Composer\Autoload\includeFile',
		'args' => [
			(int) 0 => '/var/www/cake_app/vendor/composer/../cakephp/cakephp/src/Network/Request.php'
		]
	],
	(int) 3 => [
		'function' => 'loadClass',
		'class' => 'Composer\Autoload\ClassLoader',
		'object' => object(Composer\Autoload\ClassLoader) {},
		'type' => '->',
		'args' => [
			(int) 0 => 'Cake\Network\Request'
		]
	],
	(int) 4 => [
		'file' => '/var/www/cake_app/config/bootstrap.php',
		'line' => (int) 168,
		'function' => 'spl_autoload_call',
		'args' => [
			(int) 0 => 'Cake\Network\Request'
		]
	],
	(int) 5 => [
		'file' => '/var/www/cake_app/vendor/cakephp/cakephp/src/Http/BaseApplication.php',
		'line' => (int) 145,
		'args' => [
			(int) 0 => '/var/www/cake_app/config/bootstrap.php'
		],
		'function' => 'require_once'
	],
	(int) 6 => [
		'file' => '/var/www/cake_app/vendor/cakephp/cakephp/src/Http/Server.php',
		'line' => (int) 121,
		'function' => 'bootstrap',
		'class' => 'Cake\Http\BaseApplication',
		'object' => object(App\Application) {},
		'type' => '->',
		'args' => []
	],
	(int) 7 => [
		'file' => '/var/www/cake_app/vendor/cakephp/cakephp/src/Http/Server.php',
		'line' => (int) 82,
		'function' => 'bootstrap',
		'class' => 'Cake\Http\Server',
		'object' => object(Cake\Http\Server) {},
		'type' => '->',
		'args' => []
	],
	(int) 8 => [
		'file' => '/var/www/cake_app/webroot/index.php',
		'line' => (int) 37,
		'function' => 'run',
		'class' => 'Cake\Http\Server',
		'object' => object(Cake\Http\Server) {},
		'type' => '->',
		'args' => []
	]
]
$frame = [
	'file' => '/var/www/cake_app/vendor/composer/ClassLoader.php',
	'line' => (int) 444,
	'args' => [
		(int) 0 => '/var/www/cake_app/vendor/cakephp/cakephp/src/Network/Request.php'
	],
	'function' => 'include'
]
deprecationWarning - CORE/src/Core/functions.php, line 312
include - CORE/src/Network/Request.php, line 4
Composer\Autoload\includeFile - ROOT/vendor/composer/ClassLoader.php, line 444
Composer\Autoload\ClassLoader::loadClass() - ROOT/vendor/composer/ClassLoader.php, line 322
spl_autoload_call - [internal], line ??
require_once - ROOT/config/bootstrap.php, line 168
Cake\Http\BaseApplication::bootstrap() - CORE/src/Http/BaseApplication.php, line 145
Cake\Http\Server::bootstrap() - CORE/src/Http/Server.php, line 121
Cake\Http\Server::run() - CORE/src/Http/Server.php, line 82
[main] - ROOT/webroot/index.php, line 37
```

**Comment by dereuromark** [comment] 2018-05-21 19:57
As you can see it is your webroot's index.php, you need to update also skeleton files
The improved [upgrade](https://github.com/dereuromark/upgrade) app also provides a "skeleton" command for exactly that, but simple copy and paste also does the trick.

Closing then as invalid.

**Closed by dereuromark** 2018-05-21 19:57 UTC

**Comment by smarek** [comment] 2018-05-21 20:02
Oh, so is this mentioned somewhere in documentation, or how should I know this?

**Comment by dereuromark** [comment] 2018-05-21 20:06
This is the normal upgrade path when doing minor upgrades.
This is linked and mentioned at https://book.cakephp.org/3.0/en/appendices/3-0-migration-guide.html etc

**Comment by smarek** [comment] 2018-05-21 20:17
I don't really see it there, as I was upgrading from 3.x to 3.x version, i didn't suspect anything like that.

Similar issue I found, while searching for solution in my case, was #12068, which was solved by replacing `bin/cake` with new version.

In my opinion, in files, that are not usually user modified (skeleton webroot, bin, config/bootstrap), there either should be at least warning, or if the file matches the version provided in version from which the upgrade is done, it should be migrated automatically to newer version.

Does this make any sense to you?

**Comment by dereuromark** [comment] 2018-05-21 20:21
This is not possible.
It is linked to use the upgrade plugin, and also known to check existing project files against the current app master skeleton.
Feel free to PR an additional note for clarification into the docs, though, if you think that helps others.
